'use client'

import { useState, useEffect, useRef } from 'react'
import { useParams, useSearchParams, useRouter } from 'next/navigation'
import dynamic from 'next/dynamic'

const ReportBuilder = dynamic(() => import('@/components/ReportBuilder'), { ssr: false })

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'

const STRINGS = {
  'pt-BR': { loading: 'Carregando relatório...', invalid: 'Link inválido', shared: 'Relatório Compartilhado', footer: 'Relatório gerado por' },
  'es':    { loading: 'Cargando informe...', invalid: 'Enlace inválido', shared: 'Informe Compartido', footer: 'Informe generado por' },
  'en':    { loading: 'Loading report...', invalid: 'Invalid link', shared: 'Shared Report', footer: 'Report generated by' },
  'fr':    { loading: 'Chargement du rapport...', invalid: 'Lien invalide', shared: 'Rapport Partagé', footer: 'Rapport généré par' },
  'de':    { loading: 'Bericht wird geladen...', invalid: 'Ungültiger Link', shared: 'Geteilter Bericht', footer: 'Bericht erstellt von' },
  'it':    { loading: 'Caricamento report...', invalid: 'Link non valido', shared: 'Report Condiviso', footer: 'Report generato da' },
  'zh':    { loading: '正在加载报告...', invalid: '无效链接', shared: '共享报告', footer: '报告由以下生成' },
  'ja':    { loading: 'レポートを読み込み中...', invalid: '無効なリンク', shared: '共有レポート', footer: 'レポート生成元' },
}

const LANGS = [
  { code: 'pt-BR', flag: '🇧🇷', label: 'Português' },
  { code: 'es',    flag: '🇪🇸', label: 'Español' },
  { code: 'en',    flag: '🇺🇸', label: 'English' },
  { code: 'fr',    flag: '🇫🇷', label: 'Français' },
  { code: 'de',    flag: '🇩🇪', label: 'Deutsch' },
  { code: 'it',    flag: '🇮🇹', label: 'Italiano' },
  { code: 'zh',    flag: '🇨🇳', label: '中文' },
  { code: 'ja',    flag: '🇯🇵', label: '日本語' },
]

export default function PublicReportPage() {
  const { token } = useParams()
  const searchParams = useSearchParams()
  const router = useRouter()
  const logoUrl = searchParams.get('logo')
  const langParam = searchParams.get('lang')
  const [report, setReport] = useState(null)
  const [activePageId, setActivePageId] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [langOpen, setLangOpen] = useState(false)
  const langRef = useRef(null)

  useEffect(() => {
    fetch(`${API_URL}/reports/public/${token}`)
      .then((r) => {
        if (!r.ok) throw new Error('not_found')
        return r.json()
      })
      .then(r => {
        setReport(r)
        const pages = r.pages && r.pages.length > 0 ? r.pages : [{ id: 'page_1', blocks: r.blocks || [] }]
        setActivePageId(pages[0].id)
      })
      .catch((e) => setError(e.message))
      .finally(() => setLoading(false))
  }, [token])

  useEffect(() => {
    const handleClickOutside = (e) => {
      if (langRef.current && !langRef.current.contains(e.target)) setLangOpen(false)
    }
    document.addEventListener('mousedown', handleClickOutside)
    return () => document.removeEventListener('mousedown', handleClickOutside)
  }, [])

  const switchLang = (code) => {
    setLangOpen(false)
    const params = new URLSearchParams(searchParams.toString())
    params.set('lang', code)
    router.replace(`/r/${token}?${params.toString()}`)
  }

  const lang = langParam || report?.language || 'pt-BR'
  const s = STRINGS[lang] || STRINGS['pt-BR']
  const activeLang = LANGS.find(l => l.code === lang) || LANGS[0]

  if (loading) return (
    <div className="min-h-screen bg-white flex items-center justify-center">
      <div className="text-gray-400 text-sm">{(STRINGS[langParam] || STRINGS['pt-BR']).loading}</div>
    </div>
  )

  if (error) return (
    <div className="min-h-screen bg-white flex items-center justify-center text-center">
      <div>
        <p className="text-gray-900 font-bold text-lg mb-2">{s.invalid}</p>
        <p className="text-gray-400 text-sm">{error === 'not_found' ? '' : error}</p>
      </div>
    </div>
  )

  const pages = report.pages && report.pages.length > 0 ? report.pages : [{ id: 'page_1', blocks: report.blocks || [] }]
  const activeBlocks = pages.find(p => p.id === activePageId)?.blocks || report.blocks || []

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {/* Header compacto */}
      <header className="bg-white border-b border-gray-200 px-4 py-2.5 shrink-0">
        <div className="flex items-center gap-3">
          {/* Logo */}
          {logoUrl ? (
            <img src={logoUrl} className="h-5 object-contain" alt="Logo" />
          ) : (
            <>
              <div className="w-5 h-5 rounded-sm bg-gray-950 flex items-center justify-center">
                <span className="text-white font-black text-[10px]">J</span>
              </div>
              <span className="text-gray-950 font-bold text-sm">Jarbis</span>
            </>
          )}
          <span className="text-gray-300 text-sm">·</span>
          {/* Título do relatório */}
          <span className="text-gray-700 text-sm font-medium truncate flex-1">{report.title}</span>
          {/* Language switcher */}
          <div className="relative shrink-0" ref={langRef}>
            <button
              onClick={() => setLangOpen(v => !v)}
              className="flex items-center gap-1.5 px-2 py-1 rounded-lg text-xs text-gray-500 hover:bg-gray-100 transition-colors"
            >
              <span>{activeLang.flag}</span>
              <span className="hidden sm:inline">{activeLang.label}</span>
              <svg className="w-3 h-3 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
              </svg>
            </button>
            {langOpen && (
              <div className="absolute right-0 top-full mt-1 bg-white border border-gray-200 rounded-xl shadow-lg z-50 py-1 min-w-[140px]">
                {LANGS.map(l => (
                  <button
                    key={l.code}
                    onClick={() => switchLang(l.code)}
                    className={`w-full flex items-center gap-2 px-3 py-1.5 text-xs transition-colors ${lang === l.code ? 'bg-indigo-50 text-indigo-700 font-medium' : 'text-gray-700 hover:bg-gray-50'}`}
                  >
                    <span>{l.flag}</span>
                    <span>{l.label}</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </div>
      </header>

      {/* Tabs — múltiplas páginas */}
      {pages.length > 1 && (
        <div className="flex items-center gap-1 px-4 py-2 border-b border-gray-100 bg-white shrink-0">
          {pages.map(page => (
            <button
              key={page.id}
              onClick={() => setActivePageId(page.id)}
              className={`px-3 py-1.5 text-sm rounded-lg transition-colors ${activePageId === page.id ? 'bg-indigo-600 text-white font-medium' : 'text-gray-600 hover:bg-gray-100'}`}
            >
              {page.title || page.id}
            </button>
          ))}
        </div>
      )}

      {/* Canvas — full width */}
      <main className="flex-1 px-4 py-4">
        <ReportBuilder blocks={activeBlocks} readOnly shareToken={token} locale={lang} />
      </main>

      <footer className="border-t border-gray-100 py-4 text-center text-xs text-gray-400 shrink-0">
        {s.footer} <span className="font-bold text-gray-700">Jarbis</span>
      </footer>
    </div>
  )
}
