"""add_ooh_campaigns_panels

Revision ID: 106d25e95a05
Revises: ca1307427ad2
Create Date: 2026-03-09 20:30:52.507668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '106d25e95a05'
down_revision: Union[str, None] = 'ca1307427ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ooh_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('advertiser', sa.String(length=300), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False, comment='PLANEJAMENTO, ATIVA, ENCERRADA, CANCELADA'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ooh_campaigns_tenant_id'), 'ooh_campaigns', ['tenant_id'], unique=False)
    op.create_table('ooh_panels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=True),
    sa.Column('codigo_operadora', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('cidade', sa.String(length=200), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('geocode_status', sa.String(length=20), nullable=False, comment='PENDENTE, OK, FALHOU'),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('formato', sa.String(length=50), nullable=False, comment='OUTDOOR, BACKLIGHT, FRONTLIGHT, DIGITAL, MOBILIARIO, BUSDOOR, METRO, AEROPORTO, OUTRO'),
    sa.Column('largura_m', sa.Float(), nullable=True),
    sa.Column('altura_m', sa.Float(), nullable=True),
    sa.Column('faces', sa.Integer(), nullable=False),
    sa.Column('digital', sa.Boolean(), nullable=False),
    sa.Column('iluminado', sa.Boolean(), nullable=False),
    sa.Column('operadora', sa.String(length=200), nullable=True),
    sa.Column('fluxo_diario', sa.Integer(), nullable=True, comment='Fluxo diário de pessoas informado pela operadora'),
    sa.Column('ots_mensal', sa.Integer(), nullable=True, comment='OTS (Opportunity To See) mensal fornecido'),
    sa.Column('valor_periodo', sa.Float(), nullable=True),
    sa.Column('populacao_municipio', sa.Integer(), nullable=True, comment='Populacão do município (IBGE Censo 2022)'),
    sa.Column('raio_visibilidade_m', sa.Integer(), nullable=False, comment='Raio de visibilidade estimado em metros'),
    sa.Column('alcance_estimado', sa.Integer(), nullable=True, comment='Alcance estimado de pessoas (calculado pela plataforma)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ooh_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ooh_panels_campaign_id'), 'ooh_panels', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ooh_panels_tenant_id'), 'ooh_panels', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ooh_panels_tenant_id'), table_name='ooh_panels')
    op.drop_index(op.f('ix_ooh_panels_campaign_id'), table_name='ooh_panels')
    op.drop_table('ooh_panels')
    op.drop_index(op.f('ix_ooh_campaigns_tenant_id'), table_name='ooh_campaigns')
    op.drop_table('ooh_campaigns')
    # ### end Alembic commands ###
