"""add_social_tokens

Revision ID: 2252c0fb99b1
Revises: be3ef4abf854
Create Date: 2026-03-10 05:01:32.976743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2252c0fb99b1'
down_revision: Union[str, None] = 'be3ef4abf854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
