"""initial

Revision ID: 907073d037e9
Revises: 
Create Date: 2026-03-09 18:16:42.280408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '907073d037e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False, comment='Plano de assinatura: free, starter, professional, enterprise'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('trade_name', sa.String(length=300), nullable=True, comment='Nome fantasia ou marca comercial'),
    sa.Column('vehicle_type', sa.Enum('TV_ABERTA', 'TV_PAGA', 'RADIO', 'JORNAL', 'REVISTA', 'OOH', 'CINEMA', 'DIGITAL', 'SOCIAL', 'STREAMING', 'INFLUENCER', name='vehicle_type_enum'), nullable=False),
    sa.Column('segment', sa.Enum('GENERALISTA', 'JORNALISMO', 'ENTRETENIMENTO', 'ESPORTES', 'NEGOCIOS', 'TECNOLOGIA', 'SAUDE', 'EDUCACAO', 'CULTURA', 'MODA_BELEZA', 'GASTRONOMIA', 'INFANTIL', 'RELIGIOSO', 'RURAL', 'OUTRO', name='media_segment_enum'), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', 'DESCONTINUADO', name='vehicle_status_enum'), nullable=False),
    sa.Column('coverage_scope', sa.Enum('NACIONAL', 'REGIONAL', 'LOCAL', 'INTERNACIONAL', name='coverage_scope_enum'), nullable=False),
    sa.Column('coverage_states', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Lista de UFs cobertas: ['SP', 'RJ', 'MG']"),
    sa.Column('coverage_cities', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Lista de municípios (IBGE codes)'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('parent_company', sa.String(length=300), nullable=True, comment='Grupo de comunicação proprietário'),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Dados verificados pela equipe Lumetra'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_slug'), 'vehicles', ['slug'], unique=True)
    op.create_index(op.f('ix_vehicles_status'), 'vehicles', ['status'], unique=False)
    op.create_index(op.f('ix_vehicles_vehicle_type'), 'vehicles', ['vehicle_type'], unique=False)
    op.create_table('audience_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.Enum('AUDIENCIA_MEDIA', 'SHARE', 'REACH', 'UNIQUE_VISITORS', 'PAGE_VIEWS', 'IMPRESSOES', 'OTS', 'IMPACTOS', 'SEGUIDORES', 'ENGAJAMENTO', 'TIRAGEM', 'CIRCULACAO', name='audience_metric_type_enum'), nullable=False),
    sa.Column('source', sa.Enum('KANTAR_IBOPE', 'COMSCORE', 'KANTAR_IBOPE_RADIO', 'IPCA', 'CENSIPAM', 'SECOM', 'DECLARADO', 'ESTIMADO', 'OUTRO', name='audience_source_enum'), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False, comment='Granularidade: daily, weekly, monthly, quarterly, yearly'),
    sa.Column('value', sa.Float(), nullable=False, comment='Valor principal da métrica'),
    sa.Column('universe', sa.Float(), nullable=True, comment='Universo de referência (ex: total de domicílios com TV)'),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'metric_type', 'source', 'reference_date', name='uq_audience_record')
    )
    op.create_index(op.f('ix_audience_records_reference_date'), 'audience_records', ['reference_date'], unique=False)
    op.create_index(op.f('ix_audience_records_vehicle_id'), 'audience_records', ['vehicle_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Papel no tenant: owner, admin, member, viewer'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audience_records_vehicle_id'), table_name='audience_records')
    op.drop_index(op.f('ix_audience_records_reference_date'), table_name='audience_records')
    op.drop_table('audience_records')
    op.drop_index(op.f('ix_vehicles_vehicle_type'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_status'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_slug'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
