"""add_municipios

Revision ID: ca1307427ad2
Revises: 907073d037e9
Create Date: 2026-03-09 19:02:26.224136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca1307427ad2'
down_revision: Union[str, None] = '907073d037e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codigo_ibge', sa.String(length=7), nullable=False, comment='Código de 7 dígitos do IBGE (ex: 3550308 = São Paulo)'),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False, comment='Sigla da UF (SP, RJ, MG...)'),
    sa.Column('nome_uf', sa.String(length=100), nullable=False),
    sa.Column('regiao', sa.String(length=50), nullable=False, comment='Norte, Nordeste, Centro-Oeste, Sudeste, Sul'),
    sa.Column('populacao_2022', sa.Integer(), nullable=True, comment='População residente - Censo 2022'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_ibge', name='uq_municipio_codigo_ibge')
    )
    op.create_index(op.f('ix_municipios_codigo_ibge'), 'municipios', ['codigo_ibge'], unique=False)
    op.create_index(op.f('ix_municipios_nome'), 'municipios', ['nome'], unique=False)
    op.create_index(op.f('ix_municipios_uf'), 'municipios', ['uf'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_municipios_uf'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_nome'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_codigo_ibge'), table_name='municipios')
    op.drop_table('municipios')
    # ### end Alembic commands ###
