"""add_ooh_campaign_shares

Revision ID: fc54f45ecfb1
Revises: 106d25e95a05
Create Date: 2026-03-09 20:39:39.129247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc54f45ecfb1'
down_revision: Union[str, None] = '106d25e95a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ooh_campaign_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['ooh_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ooh_campaign_shares_campaign_id'), 'ooh_campaign_shares', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ooh_campaign_shares_token'), 'ooh_campaign_shares', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ooh_campaign_shares_token'), table_name='ooh_campaign_shares')
    op.drop_index(op.f('ix_ooh_campaign_shares_campaign_id'), table_name='ooh_campaign_shares')
    op.drop_table('ooh_campaign_shares')
    # ### end Alembic commands ###
