"""
Lista curada dos principais portais digitais brasileiros.

Fonte: levantamento editorial Lumetra (baseado em SimilarWeb, IBGE/Secom e cobertura redacional).
Atualização: manual — revisar semestralmente.

Campos por portal:
  name          Nome editorial do veículo
  trade_name    Nome fantasia / marca reconhecida pelo público
  domain        Domínio principal (sem https://)
  segment       MediaSegment enum
  coverage_scope CoverageScope enum
  parent_company Grupo de comunicação
  coverage_states Lista de UFs (None = cobertura nacional)
  founded_year  Ano de lançamento
  description   Breve descrição editorial
"""

PORTALS: list[dict] = [
    # =========================================================================
    # JORNALISMO NACIONAL — GRANDES GRUPOS
    # =========================================================================
    {
        "name": "G1",
        "trade_name": "G1 - O Portal de Notícias da Globo",
        "domain": "g1.globo.com",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Globo",
        "coverage_states": None,
        "founded_year": 2006,
        "description": "Portal de notícias do Grupo Globo, líder de audiência no jornalismo digital brasileiro.",
    },
    {
        "name": "UOL",
        "trade_name": "UOL - O Melhor Conteúdo",
        "domain": "uol.com.br",
        "segment": "GENERALISTA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Folha",
        "coverage_states": None,
        "founded_year": 1996,
        "description": "Um dos maiores portais de conteúdo do Brasil, com notícias, entretenimento e serviços.",
    },
    {
        "name": "Folha de S.Paulo",
        "trade_name": "Folha",
        "domain": "folha.uol.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Folha",
        "coverage_states": None,
        "founded_year": 1921,
        "description": "Versão digital do maior jornal do Brasil em circulação.",
    },
    {
        "name": "Terra",
        "trade_name": "Terra",
        "domain": "terra.com.br",
        "segment": "GENERALISTA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Telefónica",
        "coverage_states": None,
        "founded_year": 1999,
        "description": "Portal de conteúdo e serviços digitais com forte presença em entretenimento e notícias.",
    },
    {
        "name": "R7",
        "trade_name": "R7",
        "domain": "r7.com",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Record",
        "coverage_states": None,
        "founded_year": 2010,
        "description": "Portal de notícias da Record TV, segundo maior grupo de comunicação do Brasil.",
    },
    {
        "name": "iG",
        "trade_name": "iG",
        "domain": "ig.com.br",
        "segment": "GENERALISTA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo iG",
        "coverage_states": None,
        "founded_year": 2000,
        "description": "Portal de notícias e conteúdo digital com foco em jornalismo e serviços.",
    },
    {
        "name": "O Globo",
        "trade_name": "O Globo",
        "domain": "oglobo.globo.com",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Globo",
        "coverage_states": None,
        "founded_year": 1925,
        "description": "Versão digital de um dos jornais mais influentes do Brasil.",
    },
    {
        "name": "Estadão",
        "trade_name": "Estadão",
        "domain": "estadao.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Estado",
        "coverage_states": None,
        "founded_year": 1875,
        "description": "Portal digital do O Estado de S. Paulo, referência em jornalismo econômico e político.",
    },
    {
        "name": "CNN Brasil",
        "trade_name": "CNN Brasil",
        "domain": "cnnbrasil.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Bandeirantes",
        "coverage_states": None,
        "founded_year": 2020,
        "description": "Portal do canal de notícias 24h CNN Brasil, com foco em jornalismo ao vivo.",
    },
    {
        "name": "Band",
        "trade_name": "Band.com.br",
        "domain": "band.uol.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Bandeirantes",
        "coverage_states": None,
        "founded_year": 1937,
        "description": "Portal digital do Grupo Bandeirantes de Comunicação.",
    },
    {
        "name": "Jovem Pan News",
        "trade_name": "Jovem Pan",
        "domain": "jovempan.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Jovem Pan",
        "coverage_states": None,
        "founded_year": 1944,
        "description": "Portal de notícias e conteúdo da rádio e canal de TV Jovem Pan.",
    },
    {
        "name": "SBT",
        "trade_name": "SBT",
        "domain": "sbt.com.br",
        "segment": "ENTRETENIMENTO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Silvio Santos / SBT",
        "coverage_states": None,
        "founded_year": 1981,
        "description": "Portal digital do Sistema Brasileiro de Televisão.",
    },

    # =========================================================================
    # NEGÓCIOS E FINANÇAS
    # =========================================================================
    {
        "name": "Exame",
        "trade_name": "Exame",
        "domain": "exame.com",
        "segment": "NEGOCIOS",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Abril",
        "coverage_states": None,
        "founded_year": 1967,
        "description": "Maior portal de negócios e economia do Brasil.",
    },
    {
        "name": "Valor Econômico",
        "trade_name": "Valor Econômico",
        "domain": "valor.globo.com",
        "segment": "NEGOCIOS",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Globo / Grupo Folha",
        "coverage_states": None,
        "founded_year": 2000,
        "description": "Referência em jornalismo econômico e financeiro do Brasil.",
    },
    {
        "name": "InfoMoney",
        "trade_name": "InfoMoney",
        "domain": "infomoney.com.br",
        "segment": "NEGOCIOS",
        "coverage_scope": "NACIONAL",
        "parent_company": "XP Inc.",
        "coverage_states": None,
        "founded_year": 2000,
        "description": "Portal de finanças pessoais, investimentos e economia.",
    },
    {
        "name": "Suno",
        "trade_name": "Suno",
        "domain": "suno.com.br",
        "segment": "NEGOCIOS",
        "coverage_scope": "NACIONAL",
        "parent_company": "Suno Research",
        "coverage_states": None,
        "founded_year": 2017,
        "description": "Portal especializado em investimentos, FIIs e ações.",
    },
    {
        "name": "Money Times",
        "trade_name": "Money Times",
        "domain": "moneytimes.com.br",
        "segment": "NEGOCIOS",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2017,
        "description": "Notícias sobre mercado financeiro, economia e negócios.",
    },
    {
        "name": "Brazil Journal",
        "trade_name": "Brazil Journal",
        "domain": "braziljournal.com",
        "segment": "NEGOCIOS",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2015,
        "description": "Jornalismo econômico-financeiro para investidores e executivos.",
    },

    # =========================================================================
    # POLÍTICA E ANÁLISE
    # =========================================================================
    {
        "name": "Poder360",
        "trade_name": "Poder360",
        "domain": "poder360.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Poder360",
        "coverage_states": None,
        "founded_year": 2015,
        "description": "Portal de análise política e jornalismo investigativo.",
    },
    {
        "name": "CartaCapital",
        "trade_name": "CartaCapital",
        "domain": "cartacapital.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Confiança Editorial",
        "coverage_states": None,
        "founded_year": 1993,
        "description": "Revista semanal com forte presença digital em análise política e social.",
    },
    {
        "name": "Veja",
        "trade_name": "Veja",
        "domain": "veja.abril.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Abril",
        "coverage_states": None,
        "founded_year": 1968,
        "description": "Versão digital da maior revista semanal do Brasil.",
    },
    {
        "name": "Metrópoles",
        "trade_name": "Metrópoles",
        "domain": "metropoles.com",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Digital News",
        "coverage_states": None,
        "founded_year": 2015,
        "description": "Portal de jornalismo digital nativo com forte presença em DF e cobertura nacional.",
    },
    {
        "name": "The Intercept Brasil",
        "trade_name": "The Intercept Brasil",
        "domain": "theintercept.com/brasil",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "First Look Media",
        "coverage_states": None,
        "founded_year": 2016,
        "description": "Jornalismo investigativo com foco em corrupção e direitos humanos.",
    },
    {
        "name": "Agência Pública",
        "trade_name": "Agência Pública",
        "domain": "apublica.org",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Agência Pública",
        "coverage_states": None,
        "founded_year": 2011,
        "description": "Primeira agência de jornalismo investigativo sem fins lucrativos do Brasil.",
    },
    {
        "name": "Brasil de Fato",
        "trade_name": "Brasil de Fato",
        "domain": "brasildefato.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Brasil de Fato",
        "coverage_states": None,
        "founded_year": 2003,
        "description": "Jornal digital popular com cobertura de movimentos sociais e política.",
    },
    {
        "name": "Agência Brasil",
        "trade_name": "Agência Brasil",
        "domain": "agenciabrasil.ebc.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "EBC - Empresa Brasil de Comunicação",
        "coverage_states": None,
        "founded_year": 2003,
        "description": "Agência de notícias pública oficial do governo federal.",
    },
    {
        "name": "O Antagonista",
        "trade_name": "O Antagonista",
        "domain": "oantagonista.com",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Crusoé",
        "coverage_states": None,
        "founded_year": 2016,
        "description": "Portal de análise política com estilo opinativo e investigativo.",
    },

    # =========================================================================
    # TECNOLOGIA
    # =========================================================================
    {
        "name": "TechTudo",
        "trade_name": "TechTudo",
        "domain": "techtudo.globo.com",
        "segment": "TECNOLOGIA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Globo",
        "coverage_states": None,
        "founded_year": 2010,
        "description": "Portal de tecnologia e games do Grupo Globo.",
    },
    {
        "name": "TecMundo",
        "trade_name": "TecMundo",
        "domain": "tecmundo.com.br",
        "segment": "TECNOLOGIA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Canaltech",
        "coverage_states": None,
        "founded_year": 2008,
        "description": "Portal de tecnologia, ciência e games com grande audiência jovem.",
    },
    {
        "name": "Canaltech",
        "trade_name": "Canaltech",
        "domain": "canaltech.com.br",
        "segment": "TECNOLOGIA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Canaltech",
        "coverage_states": None,
        "founded_year": 2012,
        "description": "Portal de tecnologia e ciência com foco em análises e tutoriais.",
    },
    {
        "name": "Gizmodo Brasil",
        "trade_name": "Gizmodo Brasil",
        "domain": "gizmodo.uol.com.br",
        "segment": "TECNOLOGIA",
        "coverage_scope": "NACIONAL",
        "parent_company": "G/O Media / UOL",
        "coverage_states": None,
        "founded_year": 2009,
        "description": "Versão brasileira do portal internacional de tecnologia Gizmodo.",
    },
    {
        "name": "Olhar Digital",
        "trade_name": "Olhar Digital",
        "domain": "olhardigital.com.br",
        "segment": "TECNOLOGIA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2001,
        "description": "Portal de tecnologia com cobertura de gadgets, apps e inovação.",
    },
    {
        "name": "B9",
        "trade_name": "B9",
        "domain": "b9.com.br",
        "segment": "TECNOLOGIA",
        "coverage_scope": "NACIONAL",
        "parent_company": "B9",
        "coverage_states": None,
        "founded_year": 2002,
        "description": "Portal de tecnologia, design e cultura digital com podcasts influentes.",
    },

    # =========================================================================
    # ENTRETENIMENTO E CULTURA POP
    # =========================================================================
    {
        "name": "Hypeness",
        "trade_name": "Hypeness",
        "domain": "hypeness.com.br",
        "segment": "ENTRETENIMENTO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2011,
        "description": "Portal de cultura, comportamento e lifestyle com forte presença em redes sociais.",
    },
    {
        "name": "Catraca Livre",
        "trade_name": "Catraca Livre",
        "domain": "catracalivre.com.br",
        "segment": "CULTURA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2011,
        "description": "Portal de cultura, entretenimento e eventos com foco em acesso gratuito.",
    },
    {
        "name": "Omelete",
        "trade_name": "Omelete",
        "domain": "omelete.com.br",
        "segment": "ENTRETENIMENTO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Omelete Company",
        "coverage_states": None,
        "founded_year": 1999,
        "description": "Portal de geek culture, cinema, séries e quadrinhos.",
    },
    {
        "name": "AdoroCinema",
        "trade_name": "AdoroCinema",
        "domain": "adorocinema.com",
        "segment": "ENTRETENIMENTO",
        "coverage_scope": "NACIONAL",
        "parent_company": "AlloCiné",
        "coverage_states": None,
        "founded_year": 2000,
        "description": "Maior portal de cinema do Brasil com críticas, trailers e lançamentos.",
    },
    {
        "name": "EGO / Gente",
        "trade_name": "Gente",
        "domain": "gente.globo.com",
        "segment": "ENTRETENIMENTO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Globo",
        "coverage_states": None,
        "founded_year": 2008,
        "description": "Portal de celebridades e entretenimento do Grupo Globo.",
    },
    {
        "name": "Splash UOL",
        "trade_name": "Splash",
        "domain": "splash.uol.com.br",
        "segment": "ENTRETENIMENTO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Folha / UOL",
        "coverage_states": None,
        "founded_year": 2019,
        "description": "Portal de entretenimento, celebridades e reality shows do UOL.",
    },
    {
        "name": "Quatro Rodas",
        "trade_name": "Quatro Rodas",
        "domain": "quatrorodas.abril.com.br",
        "segment": "OUTRO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Abril",
        "coverage_states": None,
        "founded_year": 1960,
        "description": "Maior portal e revista de automobilismo do Brasil.",
    },

    # =========================================================================
    # ESPORTES
    # =========================================================================
    {
        "name": "ge.globo",
        "trade_name": "ge",
        "domain": "ge.globo.com",
        "segment": "ESPORTES",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Globo",
        "coverage_states": None,
        "founded_year": 2016,
        "description": "Portal esportivo do Grupo Globo, líder em cobertura de futebol.",
    },
    {
        "name": "Lance!",
        "trade_name": "Lance!",
        "domain": "lance.com.br",
        "segment": "ESPORTES",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Lance",
        "coverage_states": None,
        "founded_year": 1997,
        "description": "Portal esportivo com foco em futebol nacional e internacional.",
    },
    {
        "name": "ESPN Brasil",
        "trade_name": "ESPN Brasil",
        "domain": "espn.com.br",
        "segment": "ESPORTES",
        "coverage_scope": "NACIONAL",
        "parent_company": "Walt Disney Company",
        "coverage_states": None,
        "founded_year": 1990,
        "description": "Portal da rede esportiva ESPN com cobertura de múltiplos esportes.",
    },
    {
        "name": "Trivela",
        "trade_name": "Trivela",
        "domain": "trivela.com.br",
        "segment": "ESPORTES",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2010,
        "description": "Portal independente especializado em futebol europeu e seleção brasileira.",
    },

    # =========================================================================
    # SAÚDE E BEM-ESTAR
    # =========================================================================
    {
        "name": "Drauzio Varella",
        "trade_name": "Drauzio Varella",
        "domain": "drauziovarella.uol.com.br",
        "segment": "SAUDE",
        "coverage_scope": "NACIONAL",
        "parent_company": "UOL",
        "coverage_states": None,
        "founded_year": 1999,
        "description": "Portal de saúde e medicina do médico Drauzio Varella.",
    },
    {
        "name": "Saúde Abril",
        "trade_name": "Saúde",
        "domain": "saude.abril.com.br",
        "segment": "SAUDE",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Abril",
        "coverage_states": None,
        "founded_year": 1984,
        "description": "Portal de saúde, nutrição e bem-estar.",
    },
    {
        "name": "Sempre Questionando",
        "trade_name": "Sempre Questionando",
        "domain": "semprequestionando.com",
        "segment": "SAUDE",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2014,
        "description": "Portal de ciência, saúde e combate à desinformação.",
    },

    # =========================================================================
    # PORTAIS REGIONAIS DE GRANDE AUDIÊNCIA
    # =========================================================================
    {
        "name": "Correio Braziliense",
        "trade_name": "Correio Braziliense",
        "domain": "correiobraziliense.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo Diários Associados",
        "coverage_states": ["DF", "GO"],
        "founded_year": 1960,
        "description": "Maior jornal do Distrito Federal com forte presença digital.",
    },
    {
        "name": "Gaúcha ZH",
        "trade_name": "GaúchaZH",
        "domain": "gauchazh.clicrbs.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo RBS",
        "coverage_states": ["RS"],
        "founded_year": 2017,
        "description": "Principal portal jornalístico do Rio Grande do Sul.",
    },
    {
        "name": "NSC Total",
        "trade_name": "NSC Total",
        "domain": "nsctotal.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo NSC",
        "coverage_states": ["SC"],
        "founded_year": 2015,
        "description": "Portal integrado de notícias de Santa Catarina.",
    },
    {
        "name": "Gazeta do Povo",
        "trade_name": "Gazeta do Povo",
        "domain": "gazetadopovo.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo Paranaense de Comunicação",
        "coverage_states": ["PR"],
        "founded_year": 1919,
        "description": "Maior jornal digital do Paraná.",
    },
    {
        "name": "A Tarde",
        "trade_name": "A Tarde",
        "domain": "atarde.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo A Tarde",
        "coverage_states": ["BA"],
        "founded_year": 1912,
        "description": "Principal portal de notícias da Bahia.",
    },
    {
        "name": "Correio 24 Horas",
        "trade_name": "Correio 24 Horas",
        "domain": "correio24horas.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo Correio",
        "coverage_states": ["BA"],
        "founded_year": 2010,
        "description": "Portal de notícias 24h da Bahia.",
    },
    {
        "name": "O Povo",
        "trade_name": "O Povo",
        "domain": "opovo.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo O Povo",
        "coverage_states": ["CE"],
        "founded_year": 1928,
        "description": "Maior jornal digital do Ceará.",
    },
    {
        "name": "Diário do Nordeste",
        "trade_name": "Diário do Nordeste",
        "domain": "diariodonordeste.verdesmares.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo Edson Queiroz",
        "coverage_states": ["CE"],
        "founded_year": 1981,
        "description": "Portal de notícias regional com forte presença no Ceará e Nordeste.",
    },
    {
        "name": "Ne10 (Jornal do Commercio)",
        "trade_name": "NE10",
        "domain": "ne10.uol.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Sistema Jornal do Commercio de Comunicação",
        "coverage_states": ["PE"],
        "founded_year": 2008,
        "description": "Portal de notícias de Pernambuco e Nordeste.",
    },
    {
        "name": "A Gazeta ES",
        "trade_name": "A Gazeta",
        "domain": "agazeta.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Rede Gazeta",
        "coverage_states": ["ES"],
        "founded_year": 1928,
        "description": "Principal portal de notícias do Espírito Santo.",
    },
    {
        "name": "O Liberal",
        "trade_name": "O Liberal",
        "domain": "oliberal.com",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo O Liberal",
        "coverage_states": ["PA"],
        "founded_year": 1946,
        "description": "Maior portal de notícias do Pará.",
    },
    {
        "name": "A Crítica AM",
        "trade_name": "A Crítica",
        "domain": "acritica.com",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo Rede Amazônica",
        "coverage_states": ["AM"],
        "founded_year": 1949,
        "description": "Principal portal de notícias do Amazonas.",
    },
    {
        "name": "Correio do Povo",
        "trade_name": "Correio do Povo",
        "domain": "correiodopovo.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo Record",
        "coverage_states": ["RS"],
        "founded_year": 1895,
        "description": "Jornal mais antigo do Rio Grande do Sul em circulação contínua.",
    },
    {
        "name": "NDMais",
        "trade_name": "NDMais",
        "domain": "ndmais.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Grupo ND",
        "coverage_states": ["SC"],
        "founded_year": 1971,
        "description": "Portal de notícias de Santa Catarina com jornalismo regional.",
    },
    {
        "name": "TNOnline",
        "trade_name": "TNOnline",
        "domain": "tnonline.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "REGIONAL",
        "parent_company": "Independente",
        "coverage_states": ["PR"],
        "founded_year": 1998,
        "description": "Portal de notícias do norte do Paraná.",
    },

    # =========================================================================
    # PORTAIS DIGITAIS NATIVOS / FACT-CHECKING
    # =========================================================================
    {
        "name": "Nexo Jornal",
        "trade_name": "Nexo Jornal",
        "domain": "nexojornal.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Nexo Jornal",
        "coverage_states": None,
        "founded_year": 2015,
        "description": "Jornalismo explicativo e contextualizado, referência em qualidade editorial.",
    },
    {
        "name": "Piauí",
        "trade_name": "Revista Piauí",
        "domain": "revistapiaui.estadao.com.br",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Estado",
        "coverage_states": None,
        "founded_year": 2006,
        "description": "Revista de jornalismo narrativo e investigativo.",
    },
    {
        "name": "Agência Lupa",
        "trade_name": "Lupa",
        "domain": "lupa.news",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2015,
        "description": "Primeira agência de fact-checking profissional do Brasil.",
    },
    {
        "name": "Aos Fatos",
        "trade_name": "Aos Fatos",
        "domain": "aosfatos.org",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2015,
        "description": "Agência de checagem de fatos e combate à desinformação.",
    },
    {
        "name": "The Brazil Report",
        "trade_name": "The Brazil Report",
        "domain": "thebrazilreport.com",
        "segment": "JORNALISMO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Independente",
        "coverage_states": None,
        "founded_year": 2017,
        "description": "Portal em inglês com jornalismo sobre o Brasil para audiência internacional.",
    },

    # =========================================================================
    # MODA E LIFESTYLE
    # =========================================================================
    {
        "name": "Vogue Brasil",
        "trade_name": "Vogue Brasil",
        "domain": "vogue.globo.com",
        "segment": "MODA_BELEZA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Condé Nast / Grupo Globo",
        "coverage_states": None,
        "founded_year": 1975,
        "description": "Maior portal de moda e beleza do Brasil.",
    },
    {
        "name": "Marie Claire Brasil",
        "trade_name": "Marie Claire",
        "domain": "marieclaire.globo.com",
        "segment": "MODA_BELEZA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Globo",
        "coverage_states": None,
        "founded_year": 1991,
        "description": "Portal de moda, beleza e comportamento feminino.",
    },
    {
        "name": "ELLE Brasil",
        "trade_name": "ELLE Brasil",
        "domain": "elle.com.br",
        "segment": "MODA_BELEZA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Hachette Filipacchi Presse",
        "coverage_states": None,
        "founded_year": 1988,
        "description": "Portal de moda, beleza e estilo de vida.",
    },

    # =========================================================================
    # GASTRONOMIA
    # =========================================================================
    {
        "name": "Tastemade Brasil",
        "trade_name": "Tastemade",
        "domain": "tastemade.com/br",
        "segment": "GASTRONOMIA",
        "coverage_scope": "NACIONAL",
        "parent_company": "Tastemade",
        "coverage_states": None,
        "founded_year": 2012,
        "description": "Portal e canal de gastronomia, viagens e lifestyle.",
    },

    # =========================================================================
    # EDUCAÇÃO
    # =========================================================================
    {
        "name": "Nova Escola",
        "trade_name": "Nova Escola",
        "domain": "novaescola.org.br",
        "segment": "EDUCACAO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Fundação Lemann",
        "coverage_states": None,
        "founded_year": 1986,
        "description": "Portal de educação para professores da rede pública brasileira.",
    },
    {
        "name": "UOL Educação",
        "trade_name": "UOL Educação",
        "domain": "educacao.uol.com.br",
        "segment": "EDUCACAO",
        "coverage_scope": "NACIONAL",
        "parent_company": "Grupo Folha / UOL",
        "coverage_states": None,
        "founded_year": 2000,
        "description": "Portal de educação com notícias sobre ensino e concursos.",
    },
]
